// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVRv2GtxhggvYucieAhwTDNC4DpFo_u_g',
    appId: '1:624574025589:web:17e1c6a520c5c1d0de0d3c',
    messagingSenderId: '624574025589',
    projectId: 'pondstat-7c430',
    authDomain: 'pondstat-7c430.firebaseapp.com',
    storageBucket: 'pondstat-7c430.firebasestorage.app',
    measurementId: 'G-FSRZ54KX1X',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASd7yrNQi9LQ0ATNREAAPeoDcHTdIXPvE',
    appId: '1:624574025589:ios:ead3ecf71ea9deddde0d3c',
    messagingSenderId: '624574025589',
    projectId: 'pondstat-7c430',
    storageBucket: 'pondstat-7c430.firebasestorage.app',
    iosBundleId: 'com.example.pondstat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASd7yrNQi9LQ0ATNREAAPeoDcHTdIXPvE',
    appId: '1:624574025589:ios:ead3ecf71ea9deddde0d3c',
    messagingSenderId: '624574025589',
    projectId: 'pondstat-7c430',
    storageBucket: 'pondstat-7c430.firebasestorage.app',
    iosBundleId: 'com.example.pondstat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVRv2GtxhggvYucieAhwTDNC4DpFo_u_g',
    appId: '1:624574025589:web:da8e87184d7e930fde0d3c',
    messagingSenderId: '624574025589',
    projectId: 'pondstat-7c430',
    authDomain: 'pondstat-7c430.firebaseapp.com',
    storageBucket: 'pondstat-7c430.firebasestorage.app',
    measurementId: 'G-6C9TTPW06J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfe701Ppxe6QxwxlNi43V_t-pX9-EtFik',
    appId: '1:624574025589:android:be3b00b465083a0fde0d3c',
    messagingSenderId: '624574025589',
    projectId: 'pondstat-7c430',
    storageBucket: 'pondstat-7c430.firebasestorage.app',
  );

}